"""initial schema

Revision ID: 4743487fc9a9
Revises: 
Create Date: 2026-04-11 18:22:04.572544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4743487fc9a9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('pm', sa.String(length=50), nullable=False),
    sa.Column('progress', sa.String(length=50), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('planned_design_time', sa.Date(), nullable=True),
    sa.Column('planned_test_submit_time', sa.Date(), nullable=True),
    sa.Column('planned_test_complete_time', sa.Date(), nullable=True),
    sa.Column('planned_release_time', sa.Date(), nullable=True),
    sa.Column('planned_delivery', sa.Date(), nullable=True),
    sa.Column('planned_duration', sa.String(length=50), nullable=True),
    sa.Column('budget', sa.String(length=100), nullable=True),
    sa.Column('change_type', sa.String(length=100), nullable=True),
    sa.Column('related_product', sa.String(length=100), nullable=True),
    sa.Column('app_count', sa.Integer(), nullable=False),
    sa.Column('project_duration', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('activities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('user', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('branch', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('test_status', sa.String(length=20), nullable=False),
    sa.Column('deploy_method', sa.String(length=50), nullable=False),
    sa.Column('unit_test', sa.String(length=20), nullable=False),
    sa.Column('code_scan', sa.String(length=20), nullable=False),
    sa.Column('code_review', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('builds',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('branch', sa.String(length=100), nullable=False),
    sa.Column('tester', sa.String(length=50), nullable=False),
    sa.Column('coverage', sa.Integer(), nullable=False),
    sa.Column('can_update_coverage', sa.Boolean(), nullable=False),
    sa.Column('build_status', sa.String(length=50), nullable=False),
    sa.Column('deploy_status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=False),
    sa.Column('creator', sa.String(length=50), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requirements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('application', sa.String(length=100), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('creator', sa.String(length=50), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('risk_type', sa.String(length=100), nullable=False),
    sa.Column('risk_item', sa.String(length=500), nullable=False),
    sa.Column('risk_status', sa.String(length=20), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('avatar', sa.String(length=10), nullable=False),
    sa.Column('emp_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_steps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('defects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('environment', sa.String(length=50), nullable=False),
    sa.Column('developer', sa.String(length=50), nullable=False),
    sa.Column('tester', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('creator', sa.String(length=50), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('requirement_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('creator', sa.String(length=50), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('planned_complete_time', sa.DateTime(), nullable=True),
    sa.Column('code_branch', sa.String(length=100), nullable=True),
    sa.Column('pre_release_time', sa.DateTime(), nullable=True),
    sa.Column('prod_release_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('creator', sa.String(length=50), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_processes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('review_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewers', sa.JSON(), nullable=True),
    sa.Column('review_time', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('comment_editable', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_processes')
    op.drop_table('test_cases')
    op.drop_table('reviews')
    op.drop_table('defects')
    op.drop_table('workflow_steps')
    op.drop_table('team_members')
    op.drop_table('risks')
    op.drop_table('requirements')
    op.drop_table('documents')
    op.drop_table('builds')
    op.drop_table('applications')
    op.drop_table('activities')
    op.drop_table('users')
    op.drop_table('projects')
    # ### end Alembic commands ###
